"""Convert OTG config to NS3 scenario script."""

from __future__ import annotations

from textwrap import dedent


def convert_to_ns3(otg_config: dict) -> str:
    """Convert OTG config dict to a standalone NS3 Python scenario script.

    Generates OnOffApplication-based traffic with rate schedule matching
    the OTG flow definitions.
    """
    flows = otg_config.get("flows", [])
    if not flows:
        raise ValueError("No flows in OTG config")

    first_flow = flows[0]
    packet = first_flow.get("packet", [])

    src_ip = "10.0.0.1"
    dst_ip = "10.0.0.2"
    protocol = "udp"
    packet_size = first_flow.get("size", {}).get("fixed", 1400)

    for header in packet:
        if "ipv4" in header:
            src_ip = header["ipv4"]["src"]["value"]
            dst_ip = header["ipv4"]["dst"]["value"]
        if "udp" in header:
            protocol = "udp"
        if "tcp" in header:
            protocol = "tcp"

    schedule = []
    for flow in flows:
        rate_bps = flow["rate"]["bps"]
        duration = flow["duration"]["fixed_seconds"]["seconds"]
        schedule.append((rate_bps, duration))

    total_duration = sum(d for _, d in schedule)
    link_speed = max(r for r, _ in schedule) * 2

    schedule_lines = _format_schedule(schedule)

    script = f"""\
#!/usr/bin/env python3
\"\"\"NS3 scenario generated by cacti-tx-gen.

Replays IX traffic pattern using OnOffApplication with rate schedule.
Total duration: {total_duration:.1f}s, {len(schedule)} time slices.
\"\"\"
import ns.core
import ns.network
import ns.internet
import ns.point_to_point
import ns.applications

SCHEDULE = [
{schedule_lines}
]

SRC_IP = "{src_ip}"
DST_IP = "{dst_ip}"
PROTOCOL = "{protocol}"
PACKET_SIZE = {packet_size}
LINK_SPEED = "{_format_link_speed(link_speed)}"


def main():
    ns.core.GlobalValue.Bind("SimulatorImplementationType",
                             ns.core.StringValue("ns3::DefaultSimulatorImpl"))

    nodes = ns.network.NodeContainer()
    nodes.Create(2)

    p2p = ns.point_to_point.PointToPointHelper()
    p2p.SetDeviceAttribute("DataRate", ns.core.StringValue(LINK_SPEED))
    p2p.SetChannelAttribute("Delay", ns.core.StringValue("1ms"))
    devices = p2p.Install(nodes)

    stack = ns.internet.InternetStackHelper()
    stack.Install(nodes)

    addr = ns.internet.Ipv4AddressHelper()
    addr.SetBase(ns.network.Ipv4Address("10.0.0.0"),
                 ns.network.Ipv4Mask("255.255.255.0"))
    interfaces = addr.Assign(devices)

    sink_addr = ns.network.InetSocketAddress(
        interfaces.GetAddress(1), 12001)

    if PROTOCOL == "udp":
        sink = ns.applications.PacketSinkHelper(
            "ns3::UdpSocketFactory", sink_addr)
    else:
        sink = ns.applications.PacketSinkHelper(
            "ns3::TcpSocketFactory", sink_addr)
    sink_app = sink.Install(nodes.Get(1))
    sink_app.Start(ns.core.Seconds(0.0))
    sink_app.Stop(ns.core.Seconds({total_duration + 1.0}))

    t_offset = 0.0
    for rate_bps, duration_sec in SCHEDULE:
        if PROTOCOL == "udp":
            factory = "ns3::UdpSocketFactory"
        else:
            factory = "ns3::TcpSocketFactory"

        on_off = ns.applications.OnOffHelper(factory, sink_addr)
        on_off.SetAttribute("DataRate",
                            ns.core.DataRateValue(
                                ns.network.DataRate(int(rate_bps))))
        on_off.SetAttribute("PacketSize",
                            ns.core.UintegerValue(PACKET_SIZE))
        on_off.SetAttribute("OnTime",
                            ns.core.StringValue(
                                "ns3::ConstantRandomVariable[Constant={{0}}]".format(
                                    duration_sec)))
        on_off.SetAttribute("OffTime",
                            ns.core.StringValue(
                                "ns3::ConstantRandomVariable[Constant=0]"))

        app = on_off.Install(nodes.Get(0))
        app.Start(ns.core.Seconds(t_offset))
        app.Stop(ns.core.Seconds(t_offset + duration_sec))
        t_offset += duration_sec

    ns.core.Simulator.Stop(ns.core.Seconds({total_duration + 2.0}))
    ns.core.Simulator.Run()
    ns.core.Simulator.Destroy()


if __name__ == "__main__":
    main()
"""

    return script


def _format_schedule(schedule: list[tuple[float, float]]) -> str:
    """Format schedule list for Python source code."""
    lines = []
    for rate, dur in schedule:
        lines.append(f"    ({int(rate)}, {dur:.3f}),")
    return "\n".join(lines)


def _format_link_speed(bps: float) -> str:
    """Format link speed for NS3 DataRate string."""
    if bps >= 1e12:
        return f"{bps/1e12:.0f}Tbps"
    if bps >= 1e9:
        return f"{bps/1e9:.0f}Gbps"
    if bps >= 1e6:
        return f"{bps/1e6:.0f}Mbps"
    return f"{bps:.0f}bps"
